### Get system1
GET http://system1.app.rwx.systems/app/api
customer-id: abc
# x-user-id: user-id-10
# x-ext-authz: allow
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiTDJGd2FRPT0iLCJuYmYiOjE1MDAwMDAwMDAsImV4cCI6MTkwMDAwMDAwMH0.aNmUrIo0H4jHFr39x0ZNQzEHpWrbGTIZHsSmKLtYVck

### Get system1
GET http://system2.app.rwx.systems/app/api


### Get system1
GET http://system2.app.rwx.systems/app/api
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiTDJGd2FRPT0iLCJuYmYiOjE1MDAwMDAwMDAsImV4cCI6MTkwMDAwMDAwMH0.aNmUrIo0H4jHFr39x0ZNQzEHpWrbGTIZHsSmKLtYVck