apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-common
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-common
  template:
    metadata:
      labels:
        app: http-common
    spec:
      containers:
        - name: http-common
          image: ghcr.io/rwxproject/web-app-node:master
          resources:
            limits:
              memory: "64Mi"
              cpu: "25m"
          env:
            - name: PORT
              value: "3000"
            - name: SRVADDR
              value: "http-app1-service"
            - name: SRVPORT
              value: "3000"
            - name: APITIME
              value: "60000"
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
