apiVersion: v1
kind: Service
metadata:
  name: http-common-service
  # annotations:
  #   service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector:
    app: http-common
  type: ClusterIP
  ports:
    - name: http-common-3000-port
      port: 3000
      targetPort: 3000
