apiVersion: v1
kind: Service
metadata:
  name: web-app-service
  # annotations:
  #   service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector:
    app: web-app
  type: ClusterIP
  ports:
    - name: web-app-3000-port
      port: 3000
      targetPort: 3000
