apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-test
spec:
  selector:
    matchLabels:
      app: node-test
  template:
    metadata:
      labels:
        app: node-test
    spec:
      containers:
        - name: node-test
          image: ghcr.io/rwxproject/node-test:0.0.1
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
