apiVersion: apps/v1
kind: Deployment
metadata:
  name: http
  namespace: istio-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-public
  template:
    metadata:
      labels:
        app: http-public
    spec:
      containers:
        - name: http
          image: ghcr.io/rwxproject/web-app-node:master
          resources:
            limits:
              memory: "64Mi"
              cpu: "25m"
          env:
            - name: PORT
              value: "3000"
            - name: SRVADDR
              value: "localhost"
            - name: SRVPORT
              value: "3000"
            - name: APITIME
              value: "60000"
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
