apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: system
spec:
  hosts:
    - "system1.app.rwx.systems"
  gateways:
    - system-gateway
  http:
    - match:
        - uri:
            prefix: /auth
      route:
        - destination:
            port:
              number: 8080
            host: keycloak.auth-system.svc.cluster.local
    - match:
        - uri:
            prefix: /app/
        - uri:
            exact: /app
          headers:
            x-jwt-claim.exp:
              exact: "3537391104"
      rewrite:
        uri: "/"
      route:
        - destination:
            port:
              number: 3000
            host: http-app1-service
